cloud:
  aws:
    region: ap-northeast-2
    stack:
      auto: false
    s3:
      img:
        bucket: popping-s3
      fcm:
        bucket: popping-fcm
        sdk: ${FCM_SDK}
      credentials:
        accessKey: ${accessKey}
        secretKey: ${secretKey}